### ISSUE TITLE
关于ameblotoken

### ISSUE THREAD

**Issue by flylzj** [aobeom/amebloimg#1]
你好，我最近在写关于ameblo的自动点赞，里面涉及到一个ameblotoken，不知道你有没有方法拿到这个token

**Comment by aobeom** [comment]
ameblotoken应该是在js里生成的，可以用selenium模拟点击 [Demo](https://github.com/aobeom/amebloimg/tree/iine)

**Comment by flylzj** [comment]
这个问题我后面解决了，谢谢
